import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono } from 'next/font/google'
import "./globals.css";
import { Header } from "../components/header/page";
import { ContactForm } from "@/components/contact-form/page";
import { Footer } from "@/components/footer/page";
import { BackToTop } from "@/components/back-to-top/page";

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const plexMono = IBM_Plex_Mono({
  variable: '--font-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.variable} ${plexMono.variable}`}
      >
        <BackToTop/>
        <Header />
        {children}
        <ContactForm/>
        <Footer/>
      </body>
    </html>
  );
}
